sprint2
ClevertecFrontendLab/sprint2-YauheniZubets pull request #1
Opened 2023-02-08 21:48 UTC by YauheniZubets

2023-02-09 17:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 1440px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/Test%20width%201440px%20--%20test%20slider%20(failed).png)
***
**Test width 768px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/Test%20width%20768px%20--%20test%20navigation%20view%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/book-page%20comment%20expand.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20after%20768px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675964823/slider%20one%20foto%20768px.png)

2023-02-09 18:23 UTC, SergeyGlazun requested changes

2023-02-09 18:23 UTC, SergeyGlazun commented on public/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1" />
![image](https://user-images.githubusercontent.com/70904466/217902595-d7b46d72-7981-488d-bf5f-6bc721efa1ba.png)
не кликаеться

2023-02-09 18:23 UTC, SergeyGlazun commented on public/index.html
> +    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
![image](https://user-images.githubusercontent.com/70904466/217902721-1408a04a-6ae3-4249-8b80-081d83a58726.png)
и тут не закрывается вне области

2023-02-09 18:23 UTC, SergeyGlazun commented on public/index.html
> +    manifest.json provides metadata used when your web app is installed on a
![image](https://user-images.githubusercontent.com/70904466/217903066-a541fd4c-822b-40de-98a7-87207bea7207.png)
не переключаеться

2023-02-09 18:23 UTC, SergeyGlazun commented on public/index.html
> +    user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
![image](https://user-images.githubusercontent.com/70904466/217903347-b57f765c-98f2-4373-9546-f20edc118dde.png) 
![image](https://user-images.githubusercontent.com/70904466/217903492-e677aa30-04a0-4ce2-9714-939afa5d6256.png)
нет одиночных книг что б проверить работу слайдера
везде книги там даже где указанно что нет обложки

2023-02-10 00:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 1440px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/Test%20width%201440px%20--%20test%20navigation%20view%20(failed).png)
***
**Test width 768px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/Test%20width%20768px%20--%20test%20navigation%20view%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1675988790/slider%20one%20foto%20768px.png)

2023-02-10 06:22 UTC, SergeyGlazun requested changes

2023-02-10 06:22 UTC, SergeyGlazun commented on src/app.js
> -
![image](https://user-images.githubusercontent.com/70904466/218017002-aaea8802-5c74-4a69-9d51-28111089cdc6.png)
не отображает книги при переходе в мобильной версии только если начть страницу расширять

2023-02-10 06:22 UTC, SergeyGlazun commented on src/app.js
>      return (
![image](https://user-images.githubusercontent.com/70904466/218017300-d51ae1af-7ba7-4e02-9b77-7f037b6bab25.png)
после расширения страницы не закрывается

2023-02-10 06:22 UTC, SergeyGlazun commented on src/app.js
>              <Routes>
![image](https://user-images.githubusercontent.com/70904466/218017529-68efdf7f-9a20-4866-b2f4-5557222d2d8f.png)
но тут у тя нормально... вобьем проверь логику отображения слайдера и если нет книг там возможно что то

2023-02-10 06:22 UTC, SergeyGlazun commented on src/app.js
>                  <Route path='/books/:all' element={<MainPage allLinks={allLinks} toogleLinks={toogleLinks} />} />
![image](https://user-images.githubusercontent.com/70904466/218017936-96dfb664-7e56-4d1d-ac24-841cebefce99.png)
в таком режиме не переходит на книгу

2023-02-10 06:22 UTC, SergeyGlazun commented on src/app.js
> -                <Route path='/book' element={<BookPage />} />
![image](https://user-images.githubusercontent.com/70904466/218018066-36d37a90-9b6f-415e-be6b-6e737f92a330.png)
два активных меню

2023-02-10 17:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 1440px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/Test%20width%201440px%20--%20test%20navigation%20view%20(failed).png)
***
**Test width 768px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/Test%20width%20768px%20--%20test%20navigation%20view%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676048692/slider%20one%20foto%20768px.png)

2023-02-10 17:12 UTC, SergeyGlazun requested changes

2023-02-10 17:12 UTC, SergeyGlazun commented on src/components/book-data/bookdata.css
> +        margin: auto;
![image](https://user-images.githubusercontent.com/70904466/218153460-377401d5-d8f3-4df4-b586-bc578724efc1.png)
не закрывает при клики в не области бургера

2023-02-10 17:40 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 1440px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/Test%20width%201440px%20--%20test%20navigation%20view%20(failed).png)
***
**Test width 768px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/Test%20width%20768px%20--%20test%20navigation%20view%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/YauheniZubets/1676050850/slider%20one%20foto%20768px.png)

2023-02-10 17:45 UTC, SergeyGlazun approved these changes

2023-02-10 17:46 UTC, merged

2023-02-10 17:47 UTC, YauheniZubets commented
Спасибо!)

2023-02-10 17:47 UTC, SergeyGlazun commented
![image](https://user-images.githubusercontent.com/70904466/218160547-e1acca36-27d6-47f6-ad0b-7cad01d5cdfb.png)
к окончанию след спринта пофиксите верстку

2023-02-10 17:48 UTC, YauheniZubets commented
Понял, сейчас займусь)

2023-02-10 17:48 UTC, SergeyGlazun commented
![image](https://user-images.githubusercontent.com/70904466/218160670-566f722a-33bc-45b0-94b5-f032c5f3cb7d.png)
и тут не выделена активная книга